import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { request } from 'node:http';
import { setTimeout as delay } from 'node:timers/promises';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';

const port = 4399;
const debugPort = 9299;
const server = spawn('npm', ['run', 'dev', '--', '--host', '127.0.0.1', '--port', String(port)], { stdio: 'ignore' });
const chrome = spawn('/home/hermes/.local/opt/google-chrome/opt/google/chrome/chrome', ['--headless=new', '--no-sandbox', '--disable-gpu', `--remote-debugging-port=${debugPort}`, `--user-data-dir=${mkdtempSync(`${tmpdir()}/footprintx-browser-`)}`], { stdio: 'ignore' });
const getJson = (path) => new Promise((resolve, reject) => { const req = request({ host: '127.0.0.1', port: debugPort, path }, (res) => { let body = ''; res.on('data', (chunk) => { body += chunk; }); res.on('end', () => resolve(JSON.parse(body))); }); req.setTimeout(1000, () => req.destroy(new Error('debug request timeout'))); req.on('error', reject); req.end(); });
const waitFor = async (fn, timeout = 15000) => { const start = Date.now(); while (Date.now() - start < timeout) { try { return await fn(); } catch { await delay(150); } } throw new Error('Timed out'); };
console.log('browser smoke: waiting for chrome and dev server');
await waitFor(async () => { await getJson('/json/version'); });
await waitFor(async () => { const res = await fetch(`http://127.0.0.1:${port}`); assert.equal(res.status, 200); });
console.log('browser smoke: attaching CDP');
const tab = await (await fetch(`http://127.0.0.1:${debugPort}/json/new?http://127.0.0.1:${port}`, { method: 'PUT' })).json();
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((resolve, reject) => { ws.addEventListener('open', resolve, { once: true }); ws.addEventListener('error', reject, { once: true }); });
let nextId = 0;
const pending = new Map();
ws.addEventListener('message', (event) => { const message = JSON.parse(event.data); if (message.id && pending.has(message.id)) { pending.get(message.id)(message); pending.delete(message.id); } });
const cdp = (method, params = {}) => new Promise((resolve) => { const id = ++nextId; pending.set(id, resolve); ws.send(JSON.stringify({ id, method, params })); });
const evaluate = async (expression) => (await cdp('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true })).result?.result?.value;
await cdp('Page.enable');
await cdp('Network.enable');
await cdp('Page.navigate', { url: `http://127.0.0.1:${port}` });
await waitFor(async () => assert.equal(await evaluate("document.querySelector('[role=dialog]')?.getAttribute('aria-modal')"), 'true'));
assert.equal(await evaluate("document.querySelectorAll('main button, aside button').length"), 0, 'release controls must not exist before acknowledgement');
assert.equal(await evaluate("document.activeElement?.id"), 'gate-title', 'gate heading receives initial focus');
await evaluate("document.querySelector('input[type=checkbox][aria-label*=lawful]').click()");
await evaluate("document.querySelector('button:not([disabled])').click()");
await evaluate("document.querySelector('input[type=radio]').click()");
await evaluate("document.querySelector('button:not([disabled])').click()");
await evaluate("document.querySelector('input[aria-label*=provider]').click()");
await evaluate("document.querySelector('button:not([disabled])').click()");
await waitFor(async () => assert.equal(await evaluate("document.querySelector('[role=dialog]') === null"), true));
assert.equal(await evaluate("document.querySelector('h1')?.textContent?.includes('FootPrintX')"), true, 'application is available only after acknowledgement');
assert.equal(await evaluate("document.querySelector('a[href^=\"https://\"]') !== null"), true);
const css = await (await fetch(`http://127.0.0.1:${port}/index.css`)).text();
assert.match(css, /prefers-reduced-motion/);
assert.match(css, /focus-visible/);
const headings = await evaluate("[...document.querySelectorAll('button')].every((button) => Boolean(button.textContent?.trim() || button.getAttribute('aria-label')))");
assert.equal(headings, true, 'all buttons have accessible names');
const targetRequests = [];
ws.addEventListener('message', (event) => { const message = JSON.parse(event.data); if (message.method === 'Network.requestWillBeSent' && /google|bing|yandex/i.test(message.params.request.url)) targetRequests.push(message.params.request.url); });
await evaluate("[...document.querySelectorAll('button')].find((button) => button.textContent?.includes('Instagram'))?.click()");
await waitFor(async () => assert.equal(await evaluate("document.querySelector('input[placeholder=\"username\"]') !== null"), true), 3000);
await evaluate("(() => { const input = document.querySelector('input[placeholder=\\\"username\\\"]'); const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set; setter.call(input, 'authorized_test'); input.dispatchEvent(new Event('input', { bubbles: true })); input.dispatchEvent(new Event('change', { bubbles: true })); })()");
await waitFor(async () => assert.equal(await evaluate("document.querySelector('button[aria-label^=\"Open query in\"]') !== null"), true), 3000);
await delay(100);
assert.equal(targetRequests.length, 0, 'generation does not request a provider');
await evaluate("document.querySelector('button[aria-label^=\"Copy\"]')?.click()");
await delay(100);
assert.equal(targetRequests.length, 0, 'copy does not request a provider');
await evaluate("document.querySelector('button[aria-label^=\"Open query in\"]')?.click()");
await waitFor(async () => assert.equal(await evaluate("document.querySelector('[role=alertdialog]') !== null"), true), 3000);
const confirmedNavigation = await evaluate("(() => { const link = document.querySelector('[role=alertdialog] a[aria-label^=\\\"Confirm and open\\\"]'); if (!link) return null; window.__confirmedNavigations = 0; link.addEventListener('click', () => { window.__confirmedNavigations += 1; }, { once: true }); return { href: link.href, label: link.getAttribute('aria-label') }; })()");
assert.match(confirmedNavigation.href, /^https:\/\/(www\.)?(google|bing|yandex)\./i, 'confirmation points at a supported provider');
await evaluate("document.querySelector('[role=alertdialog] a[aria-label^=\"Confirm and open\"]')?.click()");
await delay(250);
assert.equal(await evaluate('window.__confirmedNavigations'), 1, 'exactly one user-confirmed provider navigation is emitted');
for (const width of [320, 375, 768, 1024, 1280, 1920]) {
  await cdp('Emulation.setDeviceMetricsOverride', { width, height: 900, deviceScaleFactor: 1, mobile: false });
  assert.equal(await evaluate('document.documentElement.scrollWidth <= window.innerWidth'), true, `no horizontal overflow at ${width}px`);
}
await cdp('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false });
await cdp('Emulation.setPageScaleFactor', { pageScaleFactor: 2 });
assert.equal(await evaluate('document.documentElement.scrollWidth <= window.innerWidth'), true, 'no horizontal overflow at 200% zoom');
await cdp('Emulation.setPageScaleFactor', { pageScaleFactor: 1 });
console.log('browser smoke: gate, focus, named controls, reduced motion, axe-ready markup, six widths, 200% zoom, and explicit one-shot provider egress passed');
ws.close();
server.kill('SIGTERM');
chrome.kill('SIGTERM');
